### ISSUE TITLE
Notice about some work I'm doing

### ISSUE THREAD

**Issue by favna** [iAroc/iAroc.github.io#2]
Don't really see any other way to easily let you know other than github issues but I'd just like to let you know that I'm recreating your website's HTML/CSS side of things to use Bootsrap v4 and I'm also adding many modern-ish principles. It will likely be various days until I have anything really to show for and since it is of most interest to me I have started this process on the Hyrule Warriors site. 

Currently I've re-made the site up till the editor tabs, the source of which you can find on [my fork](https://github.com/Favna/iAroc.github.io), and here is a screenshot:

![image](https://user-images.githubusercontent.com/4019718/43295335-9528f032-9144-11e8-8af6-7627259be871.png)

Note: `choose file` changes to the file name once a file is selected

Concerning those so called "modernish principles", this is mostly reflected in the `head`, for example I added cross platform supported favicons, defined the bootstrap viewport, restructured the folder structure, set the SEO meta tags, included the HTML5 shim and more to come. Maybe most importantly I would say however is to stick exclusively to Bootstrap's grid layout system and not defining margins manually like you did. While there is nothing per se wrong with your method, the grid layout offers true cross-device-size compatibility which is what Bootstrap is all about.

---

Edit: One thing I might also consider adding, but that will be the last thing after it is all working, is a dark mode switch. Gotta save those eyes. For this however I'd like to hear from you whether you'd like dark or light mode to be the default. You can check [my own site](https://favna.xyz) for how I implemented dark mode there if you'd like, while that does use AngularJS it is totally doable in the same way with just JQuery.

**Comment by favna** [comment]
Update: I've done some more work and I would really like it if we could talk about the site a bit as there are various aspects I need to be able to discuss with you. Do you have Discord, Twitter or Facebook? My preference goes to the former, so if you have Discord please add me with `Favna#0001`, or on Twitter as `@Favna_`

Regardless, new screenshot:

![image](https://user-images.githubusercontent.com/4019718/43341282-48428d3c-91df-11e8-8fab-00123c79e27a.png)

**Comment by iAroc** [comment]
yo, i added you on discord, so we can talk there easier ;)
